---

apiVersion: skaffold/v2beta19
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        - image: devopshelper_bot
    deploy:
      kubeContext: minikube
      kustomize:
        paths:
          - "k8s/environments/dev"
  - name: prod
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_VERSION}}"
      artifacts:
        - image: asgoret/devopshelper_bot
      local:
        push: true
